### ISSUE TITLE
login and logout does not work in user menu when click

### ISSUE THREAD

**Issue by cuno92** [vb-consulting/RazorSvelte#15]
![image](https://user-images.githubusercontent.com/58431215/232386927-8eeb9766-f6e9-4f4c-9ec8-8ba2fbc14c23.png)

**Comment by vbilopav** [comment]
It doesn't work out of the box, you need to configure your external provider in configuration file, see this

https://github.com/vb-consulting/RazorSvelte#how-can-i-use-external-logins-from-google-linkedin-or-github-from-this-example

**Comment by cuno92** [comment]
> It doesn't work out of the box, you need to configure your external provider in configuration file, see this
> 
> https://github.com/vb-consulting/RazorSvelte#how-can-i-use-external-logins-from-google-linkedin-or-github-from-this-example

thanks for support, i already add github auth provider and can login via github, but after login i can't use the button in menu bar to logout, you can see the video demo below

https://user-images.githubusercontent.com/58431215/232667347-dc0d1619-9eef-4176-8b2d-2783ed69b578.mp4

**Comment by vbilopav** [comment]
I'll look it up in more details tonight, last time I checked it worked for me.
