### ISSUE TITLE
npm ERR! Missing script: "frontend-build-all"

### ISSUE THREAD

**Issue by Saad5400** [vb-consulting/RazorSvelte#17]
RazorSvelte.csproj in the Carbon UI template

`<PreBuildEvent>npm run frontend-build-all --color=always</PreBuildEvent>`

should be changed to

`<PreBuildEvent>npm run fe-build-all --color=always</PreBuildEvent>`

**Comment by vbilopav** [comment]
I don't maintain the Carbon UI template anymore. It's just an example. The master branch contains a modified Bootstrap template which I do maintain.
