### ISSUE TITLE
How to use tailwind with this template?

### ISSUE THREAD

**Issue by Bewinxed** [vb-consulting/RazorSvelte#20]
Hello! Thank you so much for this template, I’m trying to use it, but I’m not sure how to add tailwind to this.

thank you

**Comment by vbilopav** [comment]
Hi,

well, I guess you'd first have to remove the bootstrap and then add the tailwind. Presumably by using NPM.

**Comment by Bewinxed** [comment]
I already did that, The way it was installed usually is either with PostCSS
https://tailwindcss.com/docs/installation/using-postcss
or adding the autoprefixer like here
https://tailwindcss.com/docs/guides/sveltekit

and adding vitePreprocess to vite, but since this is using rollup I'm a bit
stuck, not sure where to add it.
